AWSTemplateFormatVersion: "2010-09-09"

Description: Deploy an EC2 instance into an existing VPC for deployment of Unity

Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into an existing VPC

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Basic configuration
        Parameters:
          - VPCID
          - PrivateSubnetID
          - KeyPairName
          - InstanceType
          - PrivilegedPolicyName
    ParameterLabels:
      VPCID:
        default: VPC ID
      PrivateSubnetID:
        default: Private subnet ID
      KeyPairName:
        default: SSH key name
      InstanceType:
        default: EC2 instance type
      PrivilegedPolicyName:
        default: Privileged (admin-level) IAM policy name

Parameters:
  VPCID:
    Description: ID of your existing VPC (e.g., vpc-0343606e).
    Type: AWS::EC2::VPC::Id

  PrivateSubnetID:
    Description: ID of the private subnet in an Availability Zone of your existing VPC (e.g., subnet-fe9a8b32).
    Type: AWS::EC2::Subnet::Id

  KeyPairName:
    Description: Name of an existing key pair, which allows you to securely connect to your instance after it launches.
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: EC2 instance type
    Type: String
    AllowedValues:
      - c3.xlarge
      - c4.xlarge
      - c5.xlarge
      - c6i.xlarge
    Default: c6i.xlarge
    ConstraintDescription: must be a valid EC2 instance type.

  PrivilegedPolicyName:
    Description: Name of an existing IAM policy which allows privileged access to AWS services.
    Type: String
    Default: mcp-tenantOperator-AMI-APIG

Mappings:
  AWSRegion2AMI:
    us-east-1:
      HVM64: ami-06e19b474320acfa8
    us-east-2:
      HVM64: ami-0a847dcd32f366120
    us-west-1:
      HVM64: ami-0b7451f34d8d9447a
    us-west-2:
      HVM64: ami-0f03d969d430caf73

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        # TODO: need to generalize for JPL, MCP and normal AWS accounts; currently these are specific to MCP
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/${PrivilegedPolicyName}"
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/DatalakeKinesisPolicy"
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/McpToolsAccessPolicy"
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/${PrivilegedPolicyName}"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole

  DeployerInstance:
    CreationPolicy:
      ResourceSignal:
        Timeout: PT60M
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          deployer_install:
            - install_cfn
            - install_deployer_tools
            - create_eks_cluster
            - deploy_sps
            - deploy_unity-on-demand-api
        install_cfn:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack= ${AWS::StackId}
                region=${AWS::Region}
              group: root
              mode: "000400"
              owner: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.DeployerInstance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource DeployerInstance --configsets deployer_install --url https://stackbuilder.amazonaws.com
              group: root
              mode: "000400"
              owner: root
          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
        install_deployer_tools:
          files:
            /home/ec2-user/.bash_profile:
              content: !Sub |
                # .bash_profile
                
                # Get the aliases and functions
                if [ -f ~/.bashrc ]; then
                        . ~/.bashrc
                fi
                
                # User specific environment and startup programs
                
                PATH=$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH
                
                export PATH
              group: ec2-user
              mode: "000644"
              owner: ec2-user
          packages:
            yum:
              docker: []
              git: []
          services:
            sysvinit:
              docker:
                enabled: true
                ensureRunning: true
          commands:
            01_install_eksctl:
              command: !Sub |
                set -ex \
                && echo "running 01_install_eksctl" \
                && curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp \
                && mv /tmp/eksctl /usr/local/bin \
                && chmod +x /usr/local/bin/eksctl \
                && ln -s /usr/local/bin/eksctl /bin/eksctl
              test: !Sub |
                $(eksctl version >/dev/null 2>&1 </dev/null); (( $? != 0 ))
            02_install_kubectl:
              # TODO: install the version of kubectl that matches the k8s server version specified above
              command: !Sub |
                set -ex \
                && echo "running 02_install_kubectl" \
                && curl --silent -o /tmp/kubectl https://s3.${AWS::Region}.amazonaws.com/amazon-eks/1.24.7/2022-10-31/bin/linux/amd64/kubectl \
                && mv /tmp/kubectl /usr/local/bin \
                && chmod +x /usr/local/bin/kubectl \
                && ln -s /usr/local/bin/kubectl /bin/kubectl
              test: !Sub |
                $(kubectl version --client >/dev/null 2>&1 </dev/null); (( $? != 0 ))
            03_docker_for_ec2_user:
              command: !Sub |
                set -ex \
                && echo "running 03_docker_for_ec2_user" \
                && usermod -a -G docker ec2-user
            04_install_tfenv:
              command: !Sub |
                set -ex \
                && echo "running 04_install_tfenv" \
                && git clone --depth=1 https://github.com/tfutils/tfenv.git /home/ec2-user/.tfenv \
                && chown -R ec2-user:ec2-user /home/ec2-user/.tfenv \
                && ln -s /home/ec2-user/.tfenv/bin/* /usr/local/bin
            05_clone_unity_sps_repo:
              command: !Sub |
                set -ex \
                && echo "running 05_clone_unity_sps_repo" \
                && git clone https://github.com/unity-sds/unity-sps-prototype.git /home/ec2-user/unity-sps-prototype \
                && chown -R ec2-user:ec2-user /home/ec2-user/unity-sps-prototype
            06_remove_outdated_awscli:
              command: !Sub |
                set -ex \
                && echo "running 06_remove_outdated_awscli" \
                && yum remove awscli -y \
                && ln -s /usr/local/bin/aws /bin/aws
            07_install_serverless:
              command: !Sub |
                set -ex \
                && echo "running 07_install_serverless" \
                && curl -sSL https://repo.anaconda.com/miniconda/Miniconda3-py39_22.11.1-1-Linux-x86_64.sh -o /tmp/install_miniconda.sh \
                && chmod 755 /tmp/install_miniconda.sh \
                && /tmp/install_miniconda.sh -b -p /usr/local -u \
                && conda install -y nodejs \
                && npm install -g serverless
        create_eks_cluster:
          files:
            /home/ec2-user/eksctl-config.yaml:
              content: !Sub |
                apiVersion: eksctl.io/v1alpha5
                kind: ClusterConfig
                
                iam:
                  serviceRoleARN:
                  serviceRolePermissionsBoundary: arn:aws:iam::${AWS::AccountId}:policy/${PrivilegedPolicyName}
                  withOIDC: false
                
                metadata:
                  # TODO: make this a parameter
                  name: unity-sps-on-demand
                  region: ${AWS::Region}
                  # TODO: make this a parameter
                  version: "1.24"
                  tags:
                    # TODO: make these parameters
                    service: "MAAP-HEC"
                    project: "MAAP-HEC"
                
                vpc:
                  subnets:
                    private:
                      # TODO: make these parameters
                      us-west-2b: { id: subnet-01dd01ca997ebc233 }
                      us-west-2a: { id: subnet-0379747e5833aa2c5 }
                    public:
                      # TODO: make these parameters
                      us-west-2b: { id: subnet-047ca90901d826d96 }
                      us-west-2a: { id: subnet-0bb48585d511aaf74 }
                  securityGroup:
                  sharedNodeSecurityGroup:
                  manageSharedNodeSecurityGroupRules: true
                
                managedNodeGroups:
                  - name: defaultgroupNodeGroup
                    minSize: 1
                    maxSize: 2
                    desiredCapacity: 1
                    # TODO: make this a parameter
                    instanceType: m6i.xlarge
                    ami: ami-0886544fa915698f0
                    amiFamily: AmazonLinux2
                    spot: true
                    tags:
                      # TODO: make these parameters
                      service: "MAAP-HEC"
                      project: "MAAP-HEC"
                    iam:
                      attachPolicyARNs:
                        - arn:aws:iam::${AWS::AccountId}:policy/DatalakeKinesisPolicy
                        - arn:aws:iam::${AWS::AccountId}:policy/McpToolsAccessPolicy
                        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
                        - arn:aws:iam::aws:policy/AmazonS3FullAccess
                        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
                        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
                        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
                        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
                        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
                        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
                      instanceRoleARN:
                      instanceRolePermissionsBoundary: arn:aws:iam::${AWS::AccountId}:policy/${PrivilegedPolicyName}
                      withAddonPolicies:
                        autoScaler: true
                    privateNetworking: true
                    overrideBootstrapCommand: |
                      #!/bin/bash
                      /etc/eks/bootstrap.sh unity-sps-on-demand
              group: ec2-user
              mode: '000644'
              owner: ec2-user
          commands:
            01_create_cluster:
              command: !Sub |
                set -ex \
                && echo "running 01_create_cluster" \
                && sudo -i -u ec2-user eksctl create cluster -f eksctl-config.yaml
              cwd: /home/ec2-user
            02_configure_cluster:
              command: !Sub |
                set -ex \
                && echo "running 02_configure_cluster" \
                && sudo -i -u ec2-user aws eks update-kubeconfig --region ${AWS::Region} --name unity-sps-on-demand \
                && sudo -i -u ec2-user kubectl set env daemonset -n kube-system aws-node AWS_VPC_K8S_CNI_EXTERNALSNAT=true \
                && sudo -i -u ec2-user eksctl create iamidentitymapping --cluster unity-sps-on-demand --region=${AWS::Region} --arn arn:aws:iam::${AWS::AccountId}:role/mcp-tenantDeveloper --group system:masters --username admin \
                && sudo -i -u ec2-user eksctl create iamidentitymapping --cluster unity-sps-on-demand --region=${AWS::Region} --arn arn:aws:iam::${AWS::AccountId}:role/mcp-tenantOperator --group system:masters --username admin \
                && sudo -i -u ec2-user kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.14"
              cwd: /home/ec2-user
        deploy_sps:
          files:
            /home/ec2-user/unity-sps-prototype/terraform-unity/terraform.tfvars:
              content: !Sub |
                celeryconfig_filename       = "celeryconfig_remote.py"
                container_registry_owner    = ""
                container_registry_pat      = ""
                container_registry_server   = ""
                container_registry_username = ""
                counter                     = "1"
                datasets_filename           = "datasets.remote.template.json"
                deployment_environment      = "mcp"
                docker_images = {
                  "ades_wpst_api": "ghcr.io/unity-sds/unity-sps-prototype/ades-wpst-api:unity-v0.0.1",
                  "busybox": "k8s.gcr.io/busybox",
                  "hysds_core": "ghcr.io/unity-sds/unity-sps-prototype/hysds-core:unity-v0.0.1",
                  "hysds_factotum": "ghcr.io/unity-sds/unity-sps-prototype/hysds-factotum:unity-v0.0.1",
                  "hysds_grq2": "ghcr.io/unity-sds/unity-sps-prototype/hysds-grq2:unity-v0.0.1",
                  "hysds_mozart": "ghcr.io/unity-sds/unity-sps-prototype/hysds-mozart:unity-v0.0.1",
                  "hysds_ui": "ghcr.io/unity-sds/unity-sps-prototype/hysds-ui-remote:unity-v0.0.1",
                  "hysds_verdi": "ghcr.io/unity-sds/unity-sps-prototype/hysds-verdi:unity-v0.0.1",
                  "logstash": "docker.elastic.co/logstash/logstash:7.10.2",
                  "mc": "minio/mc:RELEASE.2022-03-13T22-34-00Z",
                  "minio": "minio/minio:RELEASE.2022-03-17T06-34-49Z",
                  "rabbitmq": "rabbitmq:3-management",
                  "redis": "redis:latest"
                }
                kubeconfig_filepath = "~/.kube/config"
                mozart_es = {
                  "volume_claim_template": {
                    "storage_class_name": "gp2-sps"
                  }
                }
                namespace = "hysds"
                node_port_map = {
                  "ades_wpst_api_service": 30011,
                  "grq2_es": 30012,
                  "grq2_service": 30002,
                  "hysds_ui_service": 30009,
                  "minio_service_api": 30007,
                  "minio_service_interface": 30008,
                  "mozart_es": 30013,
                  "mozart_service": 30001,
                  "rabbitmq_mgmt_service_cluster_rpc" : 30003,
                  "rabbitmq_service_cluster_rpc" : 30006,
                  "rabbitmq_service_epmd" : 30004,
                  "rabbitmq_service_listener" : 30005,
                  "redis_service" : 30010
                }
                project = "maap-hec"
                service_port_map = {
                  "mozart_service" : 48888,
                  "grq2_service" : 48878,
                  "rabbitmq_mgmt_service_cluster_rpc" : 55672,
                  "rabbitmq_service_epmd" : 44369,
                  "rabbitmq_service_listener" : 45672,
                  "rabbitmq_service_cluster_rpc" : 55672,
                  "minio_service_api" : 49000,
                  "minio_service_interface" : 49001,
                  "hysds_ui_service" : 43000,
                  "redis_service" : 46379,
                  "ades_wpst_api_service" : 45001,
                  "grq2_es" : 49201,
                  "mozart_es" : 49200
                }
                service_type       = "LoadBalancer"
                uds_client_id      = ""
                uds_dapa_api       = ""
                uds_staging_bucket = ""
                venue              = "dev"
              group: ec2-user
              mode: '000644'
              owner: ec2-user
          commands:
            01_terraform_init:
              command: !Sub |
                set -ex \
                && echo "running 01_terraform_init" \
                && sudo -i -u ec2-user tfenv install \
                && sudo -u ec2-user /usr/local/bin/terraform init
              cwd: /home/ec2-user/unity-sps-prototype/terraform-unity
            # NOTE: create gp2-sps storageclass and set as default first to avoid race conditions (2 defaults)
            02_terraform_apply_gp2-sps:
              command: !Sub |
                set -ex \
                && echo "running 02_terraform_apply_gp2-sps" \
                && sudo -u ec2-user /usr/local/bin/terraform apply -target=module.unity-sps-hysds-cluster.kubernetes_storage_class.gp2-sps -target=module.unity-sps-hysds-cluster.null_resource.unset_default -auto-approve
              cwd: /home/ec2-user/unity-sps-prototype/terraform-unity
            03_terraform_apply:
              command: !Sub |
                set -ex \
                && echo "running 03_terraform_apply" \
                && sudo -u ec2-user /usr/local/bin/terraform apply --auto-approve
              cwd: /home/ec2-user/unity-sps-prototype/terraform-unity
        deploy_unity-on-demand-api:
          commands:
            01_clone_repo:
              command: !Sub |
                set -ex \
                && echo "running 01_clone_repo" \
                && git clone https://github.com/unity-sds/unity-on-demand-api.git /home/ec2-user/unity-on-demand-api \
                && chown -R ec2-user:ec2-user /home/ec2-user/unity-on-demand-api
              cwd: /home/ec2-user
            02_run_serverless_deploy:
              command: !Sub |
                set -ex \
                && echo "running 02_run_serverless_deploy" \
                && sudo -i -u ec2-user bash -c "cd ~/unity-on-demand-api \
                   && serverless plugin install -n serverless-python-requirements \
                   && serverless plugin install -n serverless-wsgi \
                   && serverless deploy --param permissionsBoundaryPolicyName=${PrivilegedPolicyName} --region ${AWS::Region}"
              cwd: /home/ec2-user/unity-on-demand-api
    Properties:
      ImageId: !FindInMap [AWSRegion2AMI, !Ref 'AWS::Region', HVM64]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SubnetId: !Ref PrivateSubnetID
      EbsOptimized: true
      SecurityGroupIds:
        - !Ref DeployerSecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: unity-deployer-instance
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash -xe
          yum update -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource DeployerInstance --configsets deployer_install --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource DeployerInstance --region ${AWS::Region}

  DeployerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: security group for unity-deployer-instance
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: "-1"
